version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    container_name: project_nginx
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: project_app
  db:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # POSTGRES_DB: "test"
      # POSTGRES_USER: "root"
      # POSTGRES_ROOT_PASSWORD: "root"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "8101:5432"
    container_name: project_db
